### ISSUE TITLE
Rails 4 support?

### ISSUE THREAD

**Issue by naps62** [atd/rails_engine_decorators#2]
The gemspec for this is currently requiring rails '~> 3.2.8'
Is this really a requirement? i.e. is rails 4 incompatible?

**Comment by atd** [comment]
Hi @naps62 I changed the Gemfile to relax the dependency and published a new version.

AFAIK, there does not exist a reason why it should not work in Rails 4. In fact, specs are passing. Please reopen if you find further issues
