### ISSUE TITLE
Decorators are not loaded within an engine dummy app (test environment)

### ISSUE THREAD

**Issue by gonzalo-bulnes** [atd/rails_engine_decorators#6]
Hi @atd,

I want the [Simple Token Authentication](https://github.com/gonzalo-bulnes/simple_token_authentication) gem to provide some controller decorators, and would like to load them using _Rails Engine Decorators_, but I'm running into difficulties when trying to [set it up within the _Simple Token Authentication_ dummy application](https://github.com/gonzalo-bulnes/simple_token_authentication/pull/41) (I try to keep _Simple Token Authentication_ as much test-driven as possible).

Since _Rails Engine Decorators_ works as expected in a [standalone app](https://github.com/gonzalo-bulnes/rails_engine_decorators_demo/pull/1), I suspect that something in my engine setup is uncompatible with the loading mecanism your implemented; but I'm not familiar enough with engines to find what.
In fact, Cucumber, which I'm using to generate the dummy app on-the-fly might also be involved in the problem (even if I really don't think so).

At this point, I've isolated the issue within [this PR](https://github.com/gonzalo-bulnes/simple_token_authentication/pull/41), in a couple of passing/failing scenarii (see [their output on Travis](https://travis-ci.org/gonzalo-bulnes/simple_token_authentication/jobs/20898638)) and I'm running short of ideas :S! I would really appreciate if you could take a look at it and I hope you've some time to spare.

Regards!

**Comment by atd** [comment]
Hi @gonzalo-bulnes 

You will need to `require 'rails_engine_decorators'` within your `lib/simple_token_authentication.rb` file, usually before your own requires. Bundle do this for you in an application, but does not in an engine.

Take a look at social_stream-base gem for an example: 
https://github.com/ging/social_stream/blob/master/base/lib/social_stream/base.rb
https://github.com/ging/social_stream/blob/master/base/lib/social_stream/base/dependencies.rb

**Comment by gonzalo-bulnes** [comment]
Hi @atd! That was the issue, it now [works perfectly](https://travis-ci.org/gonzalo-bulnes/simple_token_authentication/jobs/20902804). Many many thanks! : )

**Comment by atd** [comment]
My pleasure!
